spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet_app?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
  liquibase:
    change-log: "classpath:config/liquibase/master.xml"