spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    #    TODO change for smth rigth decision
    properties.hibernate.enable_lazy_load_no_trans: true
    show-sql: true
    database: postgresql
  liquibase:
    change-log: "classpath:config/liquibase/master.xml"
server:
  port: 8081


logging.level.org.springframework.security: debug
