spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
  liquibase:
    change-log: "classpath:config/liquibase/master.xml"
server:
  port: 8081


logging.level.org.springframework.security: debug
